export default {
  barColor: '#b6c4fb',
  barOpacity: 0.6,
  barActiveColor: 'purple',
  barActiveOpacity: 0.9,
  globeColor: '#000105',
  globeOpacity: 0.85,
  globeRadius: 100,
  hexMargin: 0.2,
  hexRes: 3,
  highestBar: 0.5,
  tooltipActiveBackgroundColor: 'purple',
  tooltipActiveTextColor: 'white',
  tooltipsLimit: 15,
  tooltipValueSuffix: '',
};
