export default {
  barColor: '#dd176d',
  barOpacity: 0.6,
  barActiveColor: '#dd176d',
  barActiveOpacity: 0.9,
  globeColor: '#1a166e',
  globeOpacity: 0.85,
  globeRadius: 100,
  hexOpacity: 1,
  hexPadding: 0.2,
  hexRes: 3,
  highestBar: 0.5,
  activeBackgroundColor: '#dd176d',
  activeTextColor: '#fff',
  tooltipsLimit: 15,
  valueSuffix: '',
};
