export default {
  barColor: '#dd176d',
  barOpacity: 0.6,
  barActiveColor: '#dd176d',
  barActiveOpacity: 0.9,
  globeColor: '#1a166e',
  globeRadius: 100,
  dotOpacity: 1,
  dotPadding: 0.3,
  dotRes: 3,
  highestBar: 0.5,
  tooltipActiveBackgroundColor: '#dd176d',
  tooltipActiveTextColor: '#fff',
  tooltipsLimit: 15,
  tooltipValueSuffix: '',
};
